FIND_PATH(HOCR_INCLUDE_DIR HOCR.h 
  ${stereo-qpbo_SOURCE_DIR}/extern/HOCR/include/
)


IF (HOCR_INCLUDE_DIR)
  SET(HOCR_INCLUDE_FOUND "YES")
  MESSAGE(STATUS "Found HOCR include dir: ${HOCR_INCLUDE_DIR}")
ENDIF (HOCR_INCLUDE_DIR)


IF(HOCR_INCLUDE_FOUND)
  SET(HOCR_FOUND "YES")
ENDIF(HOCR_INCLUDE_FOUND)